version: '3'
services:
  app:
    user: ${UID}:${GID}
    build: .
    command: yarn serve
    entrypoint: /app/docker-entrypoint.sh
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - ~/.ssh:/home/node/.ssh
      - node_modules-store:/app/node_modules
volumes:
  node_modules-store:
